apiVersion: v1
kind: Service
metadata:
  name: hello-ruby
  labels:
    app: hello-ruby
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    service: httpd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-ruby
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-ruby
        service: httpd
    spec:
      containers:
      - name: hello-ruby
        image: nandi108/hello-ruby
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ruby-redis
  labels:
    app: hello-ruby
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    service: redisd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-ruby-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-ruby
        service: redisd
    spec:
      containers:
      - name: hello-ruby-redis
        image: nandi108/hello-ruby-redis
        ports:
        - containerPort: 6379
